* Vinhos: 2010 Reserve (Resumo das regras com foco em 2 jogadores)

Remova aleatóriamente 2 vinhedos.

Aleatóriamente selecione a ordem inicial de jogo.

Em ordem selecionada cada jogador seleciona um vinhedo da região desejada, paga seu custo, ganha o bônus relacionado da região e produz 1 vinho.
Um cubo de notoriedade é adicionado a região do vinho produzido.

#+BEGIN_QUOTE
Tudo que é adquirido do tabuleiro é pago com bagos (cash). O salário dos enólogos é pago via banco.
#+END_QUOTE

O vinho produzido leva em consideração a qualidade base do mesmo, alguns modificadores podem incrementar esse valor (vinícolas por exemplo).

A ordem de turno é novamente alterada, levando em consideração a região de menor número no mapa, do menor para o maior.

Os tile de previsão do tempo dirão quais condições climáticas serão enfrentadas no ano, quais características são tendência do ano para apreciação na feira e quais as preferências dos magnatas.

No primeiro ano o tile 0 é utilizado onde o clima não terá impacto e os magnatas não se importam com as startups do vinho.

** Início do ano

Descarte o tile de previsão do tempo (obviamente não no ano 1) e coloque o marcador de impostos (marcador do turno) no espaço inicial.

Em ordem de turno cada jogador seleciona uma ação.

Todos iniciam o jogo no espaço central do "Quadrel" e selecionam a ação desejada.

Ações adjacentes (diagonais contam) ao espaço onde se encontra o jogador são gratuitas.
Ações não adjacentes custam 1 bago pago ao banco.
Ações onde o meeple de outro jogador se encontre custam 1 bago, pago ao respectivo jogador.
Ações onde esteja o marcador de impostos (marcador do turno) custam 1 bago, pago ao banco.

Estes efeitos podem ocorrer simultaneamente caso coincidentes.
Ex: Maria usa a ação onde se encontra João e lhe paga um bago, nesse local também existe o marcador de impostos, Maria também paga um bago ao banco, gastando um total de dois bagos.

O jogador nunca pode executar a mesma ação novamente, o movimento para outra ação é sempre obrigatório. A exceção é no centro do "Quadrel" onde é possível permancer sem executar nenhuma ação (plan better).

Quando um jogador realiza a ação de passar/coletiva de imprensa, ele seleciona a sua própria ordem de turno para a ação sub-sequente.

Após a realização da segunda ação no ano o marcador passa para a fase de manutenção.

** Ações

*** 1) Vinhedos: Compre quantos quiser, mas apenas 1 por região.

- Pegue o vinhedo do topo da pilha da região desejada.
- Pague o custo em bagos (cash).
- Coloque em seu tabuleiro em um lote vazio de uma de suas fazendas, ou com outro vinhedo da mesma região do mapa e do mesmo tipo de vinho (branco ou tinto).

Caso seja o primeiro vinhedo na sua fazenda, coloque seu disco na região do mapa de onde o vinhedo fora comprado. Se possível adicione um cubo de notoriedade à região.

- Pegue o bônus da região caso se aplique.

*** 2) Vinícolas: Construa 1 ou 2 vinícolas*

Para cada vinícola construída o jogador deve:

- Pegar 1 tile de vinícola.
- Pagar 3 bagos (cash).
- Colocar a vinícola em um lote livre em uma fazenda à sua escolha em seu tabuleiro de jogador.

Cada fazenda pode ter no máximo 2 vinícolas.
Não é obrigatório que exista um vinhedo na fazenda.

Se possível adicione um cubo de notoriedade à região selecionda (caso exista um vinhedo na fazenda, dessa região), se não for, adicione o cubo à própria vinícola e aguarde o momento onde um vinhedo seja adicionado à fazenda
para colocar esse cubo na respectiva região.

*** 3) Enólogos: Contrate 1 ou 2 Enólogos.

Enólogos trabalham em vinícolas, adicionam 2 à qualidade do vinho produzido. Podem mover-se entre fazendas antes da produção.

Para cada Enólogo contratado:

- Pague 1 bago (cash).
- Coloque o mesmo sobre uma vinícola, cada vinícula comporta 1 Enólogo.

#+BEGIN_QUOTE
Fazendeiros não podem ser contratados neste modo de jogo (2010 Reserve) a única forma de obte-lôs é na região de *Ribadejo*.
#+END_QUOTE

*Para que as pŕoximas ações sejam melhor compreendidas, alguns conceitos precisam ser apresentados:*


*Envelhecendo e produzindo vinho:*

Ao final de cada ano antes da produção mova dos vinhos existentes um slot para a direita em seu depósito ou adega, representando o envelhecimento.
Quando não houver mais espaço o vinho se transforma em vinagre e é perdido.

Depois disso é possível mover cada Enólogo para uma vinícola livre.

Fazendeiros podem ser movidos para um vinhedo livre (ver a região de Ribadejo para o uso de fazendeiros).

Então a produção de vinho é iniciada:

- Calcule a qualidade do vinho.
- Pegue um tile do número apropriado.
- Coloque esse tile no espaço mais à esquerda de seu depósito ou adega. Com o lado de vinho branco ou tinto, conforme a produção do respectivo vinhedo.

*Qualidade do Vinho*

- 2 pontos para cada vinhedo na fazenda.
- 1 ponto para cada fazendeiro na fazenda.
- 1 ponto para cada vinícola na fazenda.
- 2 pontos para cada enólogo na fazenda.
- 3 pontos se estiver fazendo vinho do porto (ver a região de  Douros para o uso do vinho do porto).
- Condições climáticas de +2 até -2

#+BEGIN_QUOTE
Lembrete: Cada vinhedo pode comportar apenas 1 fazendeiro e cada vinícula apenas 1 enólogo.
#+END_QUOTE

*Valor do vinho*

- Qualidade do vinho +
- 1,3,5 de envelhecimento na adega +
- Opcionalmente 1 ou 2 pontos por cubo de notoriedade descartado da respectiva região do vinho produzido +
- 1 ponto caso o vinho seja da região de *Algarve*

*** 4) Adegas: Construa 1 adega

Ajudam que o vinho envelheça mais, aumentando seu valor. Quanto mais velho o vinho, mais valioso se torna.

- Pegue o tile de adega.
- Pague 2 bagos (cash).
- Cubra um de seus depósitos e mova os vinhos existentes para a adega.
- Se possível coloque um cubo de notoriedade em um espaço disponível na respectiva região.

Caso não exista um vinhedo na fazenda onde a adega foi colocada, deixe o cubo de notoriedade sobre a mesma, até que um vinhedo seja adquirido e colocado nessa fazenda.

*** 5) Vendas (mercado interno): Venda quantos vinhos quiser.

Para cada vinho vendido:

- Coloque 1 barril em um slot vazio de sua escolha.

O vinho deve ser do mesmo tipo (branco ou tinto) e ter no mínimo o mesmo valor do referido slot.
Uma vez vendido o barril não poderá ser movido.

- Opcionalmente remova 1 ou 2 cubos de notoriedade da região de produção de seu vinho.

Apenas faça isso para atingir o valor necessário para a venda, não é permitido usar o cubo sem efeito prático apenas para restringir o uso pelo oponente.

- Descarte o tile do vinho.
- Receba o valor da venda como crédito na conta do banco.

*Recupere pares de barris dos estabelecimentos locais:*

Durante seu turno, antes de realizar sua ação, é possível recuperar *pares* de barris dos estabelecimentos locais, cada par deve vir do mesmo estabelecimento.

Para cada par recuperado coloque 2 cubos de notoriedade em regiões diferentes do mapa a sua escolha, 1 em cada.

*** 6) Exportação: Exporte quantos vinhos quiser

A exportação provê pontos imediatos e pontuação de final de jogo.

#+BEGIN_QUOTE
Onde houver pontos circulados com uma arte em verde, estes são ganhos imediatamente. Onde essa arte for roxa, são pontuação para o final do jogo.
#+END_QUOTE

- Coloque 1 barril em um slot vazio do mercado de exportação. Este deve ser no mínimo o valor indicado no slot, cubos de notoriedade são permitidos para aumentar o valor do vinho, as regras seguem confirme descrito acima em vendas.
- Decarte o tile de vinho.

#+BEGIN_QUOTE
No jogo com 2 jogadores apenas os slots da área demarcada interna são válidos.
#+END_QUOTE

*** 7) Banco

- Retirar seus bagos do banco: Mova seu marcador para trás o número de espaços relativo ao valor do saque e pegue este montante em bagos.

Caso atinja o valor de -2VP imediatamente perca esses pontos. Não será mais possível realizar saques até que o saldo seja novamente positivo.

- Depositar seus bagos no banco: Mova seu marcador para a frente o número de espaços relativo ao montante que deseja depositar e entregue seus bagos ao banco.

O valor máximo que o banco suporta são 24 bagos na conta do jogador.

- Investimento: Invista seus bagos no banco, o valor é indicado no tabuleiro. Na fase de manutenção receba juros pelo seu investimento como crédito no banco.

*** 8) Especialistas (Sommelier)

Cada especialista pode ajudá-lo em determinada característica na feira do vinho.

Além disto cada um possui uma habilidade bônus que pode ser usada imediatamente. Para isso vire o tile do especialista para oseu verso e faça uso do bônus.

Após passada a próxima feira vire o especialista de volta para o lado da frente, a habilidade pode ser usada novamente, ou o especialista poderá participar da feira seguinte.

*** 9) Passar/Coletiva de imprensa

- Passe e não faça nada

ou

- Dê uma coletiva de imprensa.

Introduza seu vinho na próxima feira de vinhos.
Esta ação só pode ser realizada uma única vez por feira. Caso não faça a introdução de seu vinho por meio da coletiva, deverá fazê-lo diretamente no momento da feira.

- Declare qual vinho será apresentado na feira.
- Opcionalmente remova 1 ou 2 cubos de notoriedade da região de onde o vinho é proveniente para aumentar seu valor.

Isto pode ser necessário para atingir a expectativa do magnata Bruno ou apenas para apresentar um vinho e maior valor na feira.

- Ganhe os pontos de feira caso seu vinho seja de valor superior a 9, ganhe pontos pelo excedente.
- Pegue seu tile de feira de acordo com a tabela em seu tabuleiro pessoal de jogador.
- Escolha um quiosque de feira vazio e coloque seu tile nele. Pegue o bônus ofertado nele e ganhe pontos de feira de acordo com as características do vinho marcadas no quiosque. Ex: Aroma (verde), aparência (azul).
