* Twilight Struggle

** Preparação

- 3 decks: início, meio e fim da guerra

Embaralhar o deck de início da guerra e distribuir 8 cartas para cada jogador;

Cada jogador pode analisar sua mão antes do próximo passo;

O jogador da URSS é o primeiro a distribuir seus 15 pontos de influência;

- 1 Síria;
- 1 Iraque;
- 3 Coréia do Norte;
- 3 Alemanha Oriental;
- 1 Finlândia;
- Outros 6 pontos distribuídos em qualquer lugar da Europa Oriental (roxo de tonalidade mais clara);

O jogador do EUA distribui seus 23 pontos de influência;

- 1 Israel;
- 1 Irã;
- 1 Coréia do Sul;
- 1 Japão;
- 1 Filipinas;
- 4 Austrália;
- 1 Panamá;
- 1 África do Sul;
- 5 Reino Unido;
- Outros 7 pontos distribuídos em qualquer lugar da Europa Ocidental (roxo de tonalidade mais escura);

Posicionar os marcadores de corrida espacial, turno, VP na posição 0 e defcon na posição 5;

** Mapa

Dividido em 6 regiões políticas;

- América Central na cor verde, tom claro e América do Sul também na cor verde, tom escuro;

- Europa na cor roxa, sendo a parte ocidental em tom escuro e oriental em tom claro (por questões políticas Canadá e Turquia fazem parte da Europa);

- Oriente Médio na cor azul (por questões políticas Egito e Líbia fazem parte do Oriente Médio);

- África na cor amarela;

- Ásia na cor laranja;

- Sudeste da Ásia, também na cor laranja em em tom mais claro;

Cada país, ou bloco de países, é representado no mapa por um espaço retangular com duas seções à direita e à esquerda;

Cada espaço contém um número que representa a *estabilidade*, *independência* ou *nível de poder* daquele país;

Alguns países possuem o nome com o fundo azul e outros com o fundo amarelo;

Países com fundo azul são ditos países disputados ou territórios de batalha, são importantes em termos de pontuação da partida;

Ainda existem dois espaços especiais que representam as superpotências EUA e URSS;

Os países são conectados por meio de linhas que representam adjacência;

Uma linha marrom representa adjacência de países dentro de uma mesma região, uma linha tracejada vermelha representa adjacência de países entre regiões diferentes e uma linha preta representa adjacência com uma superpotência (EUA/URSS);

Cada país pode estar em um de dois estados: Controlado ou Não controlado;

- Controlado: quando o número que representa a estabilidade foi atingido pela diferença entre às influências políticas no país;

- Não controlado; quando o número de estabilidade não foi alcançado;

Ex:

Israel possui um número de estabilidade 4, se os EUA possui uma ficha de influência de valor 1 e a URSS possui uma ficha de valor 5, (5 - 1 = 4) este país *é controlado* pela URSS. Caso o saldo fosse inferior a 4 este país então
*não seria controlado*;

Para indicar o controle de determinado país, a ficha política de quem o controla deve ser colocada com o lado escuro para cima (azul para os EUA e vermelho para a URSS);

** Rodadas

O jogo é dividido em 10 rodadas;

No ínicio da guerra serão 6 turnos de ação, a partir dos meados da guerra 7 turnos de ação, nessa parte misturamos ao deck atual as cartas de meados da guerra e nas 3 rodadas finais é misturado o deck de final da guerra;

Nas rodadas de 1 à 3 o jogador completa sua mão para 8 cartas, uma carta da rodada anterior pode ser mantida, nas rodadas de 4 à 10 o jogador completa sua mão para 9 cartas, uma carta da rodada anterior pode ser mantida;

Uma rodada do jogo segue às seguintes etapas:

1 - Melhorar o nível de Defcon: subir em o nível 1 na direção do nível 5 (paz);

2 - Manchetes: cada jogador revela uma carta simultâneamente e realiza o evento descrito. O evento é resolvido na ordem do valor de operação da carta, empates vão para o lado dos EUA;

3 - Turnos: os jogadores alternam os turnos de ações, jogando uma carta por turno, 6 turnos nas rodadas de 1 à 3 e 7 turnos nas rodadas de 4 à 10. O jogador da URSS sempre joga primeiro;

Uma carta possui três características principais:

- Um alinhamento, que pode ser com os EUA (estrela branca), URSS (estrela vermelha) ou neutra (estrela meio branca, meio vermelha);

- Um valor de pontos de operação;

- Um evento;

Caso o jogador utilize uma carta com alinhamento da superpotência que representa ou neutra, este pode escolher entre usar os pontos de operação ou executar o evento;

Caso a carta selecionada tenha alinhamento com a superpotência do seu oponente, este só pode utilizar os pontos de operação e o evento acontence obrigatóriamente para o oponente, qualquer escolha orientada pelo evento
deverá ser feita pelo oponente;

Pontos de operação podem ser utilizados de algumas maneiras:

- *Adicionar influência*: Partindo de um país *onde o jogador já possua influência no início da rodada*, é possível adicionar, em um país adjacente, um ponto de influência ao custo de um ponto de operação. Caso este país
seja *controlado pelo oponente*, cada ponto de influência custa 2 pontos de operação;

Obs: Imediatamente ao adicionar influência em um país, verifique o controle, caso a influência mude a situação do país, aplique imediatamente o efeito. Pontos de influência são adicionados 1 à 1.

- *Realinhamento*: Tentativa de diminuir a influência do oponente em algum país. O jogador não adiciona sua influência no país. Cada ponto de operação representa uma tentativa de realinhamento;

O realinhamento é feito por uma rolagem de dados mais alguns modificadores:

1 - O jogador com mais influência no país ganha +1
2 - Cada país adjacente sob controle dos jogadores adiciona +1
3 - País conectado à uma superpotência adiciona +1 (para o jogador com mais influência no país)

Em caso de vitória nos dados + modificadores, a diferença entre os valores na rolagem e a influência no tabuleiro é aplicada removendo a influência do oponente;

- *Golpe*: Tentativa de mudança da composição de governo do país. O jogador propondo o golpe *NÃO* precisa ter influência no país, apenas seu oponente. O golpe é financiado pelo valor de operação da carta.

Para que um golpe seja bem sucedido, o jogador deve fazer uma rolagem de dado e este valor, somado ao valor de pontos de operação de sua carta, deverá atingir o dobro do valor de estabilidade do país alvo.

Sendo bem sucedido, a diferença entre o número alcançado na rolagem + operação e o número de estabilidade do país (dobrado) é retirado de influência de seu oponente, o excedente disso é então transformado na
sua própria influência, podendo reverter completamente o cenário político do país em questão (até mesmo obtendo o controle).

Ex:

O Irã tem estabilidade de 2 o jogador do EUA possui 1 de influência no país, o jogador da URSS executa um golpe usando uma carta com valor de operação 3, a rolagem executada também é de 3.

A diferença entre a estabilidade dobrada do Irã (2 x 2 = 4) e a rolagem + pontos de operação da carta do jogador da URSS (3 + 3 = 6) é de 2 (6 - 4 = 2), ou seja o golpe é bem sucedido e 2 influências podem ser alteradas no
país.

Primeiramente o jogador da URSS utiliza um ponto para remover a influência do jogador dos EUA que é de 1, sendo então removida completamente a influência, o jogador da URSS começa a adicionar a sua pŕopria
influência a partir do valor restante de 1. O Irã agora possui 1 de influência da URSS após o golpe.

Um golpe é considerado uma operação militar, portanto o valor dos pontos de operação da carta determina o avanço na trilha de operações militares para o jogador.

Caso o país onde o golpe foi efetuado seja um país disputado (tarja azul no nome) o nível de Defcon aumenta em 1.

- *Corrida Espacial*: Uma carta qualquer pode ser usada para financiar a corrida espacia. Cada espaço da corrida espacial possui um requisito mínimo de pontos de operação necessários e um valor em um intervalo que deve
ser alcançado na rolagem do dado.

O espaço pode conferir um bônus de pontuação, ou um efeito de jogo.

A pontuação mostrada à esquerda é válida apenas para o primeiro jogador que alcançar o respectivo espaço na corrida, o próximo ficará com a pontuação à direita.

O bônus de efeito de jogo é válido para o jogador que estiver sozinho no espaço da corrida espacial, quando o oponente o alcançar o efeito não é mais válido.

A corrida espacial só pode ser patrocinada 1 vez por turno. Existem efeitos que flexibilizam essa regra.

Obs: O marcador de pontuação funciona como um "cabo de guerra", ao marcar determinado número de pontos, o marcador avança em direção ao lado que marcou a pontuação.

*** Eventos

Cartas afiliadas à uma potência o jogador pode escolher entre executar o evento, ou usar os pontos de operação;

Caso o jogador seja de outra afiliação ele deverá usar os pontos de operação em sua jogada, porém o efeito do evento ocorre obrigatóriamente. O jogador oponente é quem faz qualquer escolha determinada pelo efeito do
evento.

Se a carta dor jogada na corrida espacial, o efeito não ocorre.

Cartas não afiliadas ou neutras, o jogador sempre poderá escolher entre usar os pontos de operação ou executar o evento.

Algumas cartas são removidas do jogo após a execução do evento, essas cartas possuem um '*'.

Certas cartas são gatilhos para outros acontecimentos e vêm com seu título sublinhado. Estas cartas mantém seu efeito ativo no jogo, marcadores acompanham esses cartas para servirem de lembrete.

A carta da China começa aberta com o jogador da URSS e lhe dá um bônus. Após ser utilizada passa fechada para o jogador dos EUA utilizar em um turno subsequente. Esse movimento representa a mudança de posição
da China durante a guerra fria.

Cartas de pontuação das regiões também são conseiderados eventos, são neutras e não possuem pontos de operação. Ao final de uma rodada é possível guardar uma carta para a pŕoxima, cartas de pontuação *NÃO* podem
ser mantidas de uma rodada para outra.


*** Defcon

Mede a tensão nuclear durante a partida.

Começa no nível mais alto (paz) 5 e oscila para baixo em direção à guerra conforme ações dos jogadores. Toda nova rodada faz que o marcador volte um nível em direção à paz.

Caso chegue ao nível 1 o jogador que iniciou a guerra é derrotado imediatamente.

Golpes em países disputados fazem o nível de Defcon baixar em direção à guerra.

Ao chegar nos níveis 4, 3 e 2 um efeito se aplica, conforme descrito no tabuleiro, ao subir novamente o nível o efeito é cancelado.

*** Operações Militares

Ao final de cada rodada cada um dos jogadores deverá ter feito um certo número de operações militares, se falhar perde pontos de vitória para seu oponente.

O número de operações militares necessárias em cada rodada é o nível que se encontra o Defcon. Se os dois jogadores perderem pontos, marque o total líquido.

Eventos de cartas de guerra também contam como operações militares, testes de realinhamento *NÃO* contam.

*** Cartas de vitória

- Presença: caso o jogador controle pelo menos um país na região;

- Predominância: o jogador controla mais países e nações disputadas que seu oponente. Pelo menos um país e uma nação disputada precisa ser controlado;

- Controle: o jogador controla todos os países disputados da região e controla mais países que o oponente;

Modificadores:

+1 para países controlados adjacentes a superpotência do oponente;

+1 para cada país disputado controlado na respectiva região;

Faz-se a soma desses critérios e a diferença é marcada para o jogador que obter a maior pontuação.

*** Condição de vitória

- Automática: quando um jogador atinge 20 VPs;

- Pontuação na Europa: quando um jogador obtem o controle da Europa;

- Guerra Nuclear: o jogador que provocar a guerra nuclear levando o nível Defcon para 1 é imediatamente derrotado;


Caso nenhuma das condições seja atingida até o final das 10 rodadas.

Todas as regiões são então pontuadas, caso algum jogador obtenha o controle da Europa é o vencedor.

Caso algum jogador chegue a 20 pontos, nesse momento a vitória automática não é considerada.

A Ásia é pontuada como uma única região, incluindo o sudeste asiático.

Quem obtiver mais pontos vence.

Caso o marcador termine no centro, há um empate.
